name: SweepWeek
version: "2.3.0"
slug: sweepweek
description: Putzplan für einen 2-Personen-Haushalt
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
ingress: true
ingress_port: 3000
panel_icon: mdi:broom
panel_title: Putzplan
options:
  back_button: false
  back_button_path: ""
schema:
  back_button: bool
  back_button_path: str?
